[package]
name = "libp2p-community-tor"
version = "0.4.0"
edition = "2021"
description = "Tor transport for libp2p"
repository = "https://github.com/hannes-furmans/libp2p-community-tor"
license = "MIT"
keywords = ["libp2p", "tor", "p2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
arti-client = "0.24.0"
futures = "0.3"
libp2p = { version = "0.53", default-features = false, features = ["tokio", "tcp", "tls"] }
tor-rtcompat = { version = "0.24.0", features = ["tokio", "rustls"] }
tokio = { version = "1.0", features = ["io-util", "rt", "rt-multi-thread", "macros"] }
tracing = "0.1.40"

[dev-dependencies]
libp2p = { version = "0.53", default-features = false, features = ["tokio", "noise", "yamux", "ping", "noise", "macros", "tcp", "tls"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
